"""
389. Find the Difference

You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

Example 1:
	Input: s = "abcd", t = "abcde"
	Output: "e"
	Explanation: 'e' is the letter that was added.

Example 2:
	Input: s = "", t = "y"
	Output: "y"

Constraints: 
	0 <= s.length <= 1000
	t.length == s.length + 1
	s and t consist of lowercase English letters.

"""

class Solution(object):
    def findTheDifference(self, s, t):
        """
        :type s: str
        :type t: str
        :rtype: str
        """
        ans = 0

        for letter in s + t:
            ans = ans ^ ord(letter)
        return chr(ans)

            
class Solution(object):
    def findTheDifference(self, s, t):
        """
        :type s: str
        :type t: str
        :rtype: str
        """
        s = list(s)
        t = list(t)
        
        # Sort both lists
        s.sort()
        t.sort()
        
        for i in range(len(s)):
            if s[i] != t[i]:
                return t[i]
        
        # The last character of t is the added letter
        return t[-1]



